import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

import LoginForm from "../components/LoginForm/LoginForm";

const Login: NextPage = () => {
  return (
    <>
      <Head>
        <title>Войти в аккаунт</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LoginForm />
    </>
  );
};

export default Login;
