import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Signin: NextPage = () => {
  return (
    <>
      <Head>
        <title>Регистрация нового аккаунта</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>Singin</p>
    </>
  );
};

export default Signin;
